### ISSUE TITLE
Modify analytics tab to load a custom PHP file

### ISSUE THREAD

**Issue by ElGabbu** [kaltura/kmc#9]
Hi 

We would like to modify the analytics tab so that instead of showing the default analytics URL ... insteand show a custom PHP/HTML based file.

So far we found that by modifing this like so:

\opt\kaltura\web\content\generatedUiConf\23\448\ui_conf_23448176__62.xml

```
            <module id="analytics" displayName="Analytics" subtab="" htmlUrl="../../analytics/index.php"/>
```

one can get the kmc to load the page as an iFrame in the <div id='server_wrap'> container. However the object element inside the <div id="flash_wrap"> is overlayed on top of the content of the <div id='server_wrap'> 

any suggestion would be greatly appreciated :)

**Comment by ElGabbu** [comment]
Managed to get his code to work around the issue, placed in the custom index.php page:

<script type='text/javascript' src='https://code.jquery.com/jquery-2.1.1.min.js'></script>

```
    <script type='text/javascript'>
        $(document).ready(function () {
            $('#flash_wrap', window.parent.document).css('display', 'none');
            $('#server_wrap', window.parent.document).css('margin-top', '0');

            $('#hTabs li a', window.parent.document).click(function(){
                var id = $(this).attr('id');
                if(id != 'analytics'){
                    $('#flash_wrap', window.parent.document).css('display', 'block');
                }
            });

        })
    </script>
```

**Comment by atarsh-zz** [comment]
Sounds like this will break the universal studio, which is an HTML tab.
you can try using the External Interface flow (I didn't try it):
htmlUrl=“ei:kmc.utils.hideFlash(true);kmc.utils.openIframe(‘your/iframe/url');” 
if this works, it will not break if for some reason "hideFlash/showFlash" changes in the future.

**Comment by ElGabbu** [comment]
Hi Atarsh ... unfortunately your solution did not work ... it triggers some sort of JS error and the page doesn't switch too the custom page. Universal studio still seems to be working correctly with my fix.

**Comment by atarsh-zz** [comment]
go for it then, but still - I'd use the kmc.utils functions mentioned in my previous comment instead of directly playing with css.

**Comment by jessp01** [comment]
Closing the issue in the hopes that others will look up and benefit from this in the future:)
